package main

import "testing"

func TestNormalizeInboundSpecDefaults(t *testing.T) {
	ns, err := normalizeInboundSpec(NewInboundSpec{Port: 12345}, map[int]bool{})
	if err != nil {
		t.Fatalf("unexpected error: %v", err)
	}
	if ns.Protocol != "vless" || ns.Network != "tcp" || ns.Security != "none" {
		t.Fatalf("unexpected defaults: %+v", ns)
	}
	if ns.Remark != "vless-12345" {
		t.Errorf("remark = %q, want vless-12345", ns.Remark)
	}
	if ns.Path != "" {
		t.Errorf("TCP should not generate a path, got %q", ns.Path)
	}
}

func TestNormalizeInboundSpecGeneratesPath(t *testing.T) {
	for _, net := range []string{"ws", "httpupgrade", "xhttp", "grpc"} {
		ns, err := normalizeInboundSpec(NewInboundSpec{Network: net, Port: 1234}, map[int]bool{})
		if err != nil {
			t.Fatalf("%s: %v", net, err)
		}
		if ns.Path == "" {
			t.Errorf("%s should generate a path automatically", net)
		}
	}
}

func TestNormalizeInboundSpecRejects(t *testing.T) {
	cases := []struct {
		name string
		spec NewInboundSpec
		used map[int]bool
	}{
		{"unknown protocol", NewInboundSpec{Protocol: "ss", Port: 1}, nil},
		{"unknown transport", NewInboundSpec{Network: "quic", Port: 1}, nil},
		{"unknown security layer", NewInboundSpec{Security: "xtls", Port: 1}, nil},
		{"REALITY with WebSocket", NewInboundSpec{Network: "ws", Security: "reality", Port: 1}, nil},
		{"port already used", NewInboundSpec{Port: 443}, map[int]bool{443: true}},
		{"Vision with WebSocket", NewInboundSpec{Network: "ws", Security: "tls", Vision: true, Port: 1}, nil},
	}
	for _, c := range cases {
		if _, err := normalizeInboundSpec(c.spec, c.used); err == nil {
			t.Errorf("%s: expected an error but validation passed", c.name)
		}
	}
}

func TestNormalizeInboundSpecVision(t *testing.T) {
	ns, err := normalizeInboundSpec(NewInboundSpec{
		Protocol: "vless", Network: "tcp", Security: "reality", Vision: true, Port: 1234,
	}, nil)
	if err != nil {
		t.Fatalf("unexpected error: %v", err)
	}
	if ns.Flow != "xtls-rprx-vision" {
		t.Errorf("Flow = %q, want xtls-rprx-vision", ns.Flow)
	}
}

// Share links generated by the panel read publicKey/fingerprint from
// realitySettings.settings. Xray itself does not need these fields, but clients
// cannot connect through panel-generated links if they are omitted.
func TestXUIStreamSettingsCarriesRealityShareFields(t *testing.T) {
	ib := &nativeInbound{
		Port: 1234, Protocol: "vless", Network: "tcp", Security: "reality",
		Reality: &realityConfig{
			Dest:        "www.tesla.com:443",
			ServerNames: []string{"www.tesla.com"},
			PrivateKey:  "priv",
			PublicKey:   "pub",
			ShortIDs:    []string{"abcd1234"},
			Fingerprint: "chrome",
		},
	}
	stream := xuiStreamSettings(ib)
	r, ok := stream["realitySettings"].(map[string]any)
	if !ok {
		t.Fatal("realitySettings is missing")
	}
	s, ok := r["settings"].(map[string]any)
	if !ok {
		t.Fatal("realitySettings.settings is missing")
	}
	if s["publicKey"] != "pub" || s["fingerprint"] != "chrome" {
		t.Errorf("share-link fields are incorrect: %+v", s)
	}
	if r["privateKey"] != "priv" {
		t.Errorf("privateKey is missing: %+v", r)
	}
}
